databases:
  - name: udn-nba-db
    plan: free
    databaseName: udn_nba
    user: udn_nba_user

services:
  - type: redis
    name: udn-nba-redis
    plan: free
    maxmemoryPolicy: allkeys-lfu
    ipAllowList: []  # only allow internal connections

  - type: web
    name: udn-nba-web
    runtime: docker
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: POSTGRES_HOST
        fromDatabase:
          name: udn-nba-db
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: udn-nba-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: udn-nba-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: udn-nba-db
          property: password
      - key: POSTGRES_PORT
        fromDatabase:
          name: udn-nba-db
          property: port
      - key: REDIS_URL
        fromService:
          name: udn-nba-redis
          type: redis
          property: connectionString

  - type: worker
    name: udn-nba-celery-worker
    runtime: docker
    dockerCommand: celery -A config worker --loglevel=info
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: POSTGRES_HOST
        fromDatabase:
          name: udn-nba-db
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: udn-nba-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: udn-nba-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: udn-nba-db
          property: password
      - key: POSTGRES_PORT
        fromDatabase:
          name: udn-nba-db
          property: port
      - key: REDIS_URL
        fromService:
          name: udn-nba-redis
          type: redis
          property: connectionString

  - type: worker
    name: udn-nba-celery-beat
    runtime: docker
    dockerCommand: celery -A config beat --loglevel=info
    plan: free
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: POSTGRES_HOST
        fromDatabase:
          name: udn-nba-db
          property: host
      - key: POSTGRES_DB
        fromDatabase:
          name: udn-nba-db
          property: database
      - key: POSTGRES_USER
        fromDatabase:
          name: udn-nba-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: udn-nba-db
          property: password
      - key: POSTGRES_PORT
        fromDatabase:
          name: udn-nba-db
          property: port
      - key: REDIS_URL
        fromService:
          name: udn-nba-redis
          type: redis
          property: connectionString
