# Generated by Django 5.1.15 on 2026-03-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField()),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField(unique=True)),
                ('content', models.TextField()),
                ('hero_image_url', models.URLField(blank=True)),
                ('hero_image_caption', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_news_publish_ad4867_idx')],
            },
        ),
    ]
